#Don't change
config-version: '4'


config:
  # lang: english / russian
  lang: russian


  # mode: tripwire / item_frame
  # This option requires a server restart
  # ------------ tripwire ------------
  # Advantage:
  #      ● async check, less lag
  #      ● Real block hitbox like vanilla
  #
  # Disadvantage:
  #      ● limited amount(127) /iainfo to see how many slots available
  #      ● visual problem when breaking crops
  #      ● Can't remove tripwire break sound
  #
  # ------------ item_frame ------------
  # Advantage:
  #      ● unlimited amount, create as many as crop types as you want
  #      ● No tripwire break sound
  #      ● Rotation
  #
  # Disadvantage:
  #      ● entities are very laggy(loading every 5~8 item frames need 0.01 mspt)
  #      ● spigot optimized the view distance of entities
  #      ● crops would go missing if there's a large amount of furniture replacing in the same tick(128 crops/tick)
  #      ● And I can't fix this in my plugin because furniture replacing is handled by ItemsAdder.
  #      ● No real block hitbox
  #      ● ItemsAdder furniture breaking sound
  #      ● itemsAdder loot system doesn't apply to furnitures.
  #
  crop-mode: tripwire



  # Should crops be planted in random rotation?
  # only works in item_frame mode
  rotation:
    enable: false
    # 4 / 8
    variant: 4



  integration:
    #integration to prevent other players' grief
    WorldGuard: false
    Kingdoms: false
    Towny: false
    Lands: false
    GriefPrevention: false
    #integration to add players' farming skill xp
    AureliumSkills: false
    mcMMO: false
    EcoSkills: false
    #integration to sync seasons
    RealisticSeasons: false



  # Mode 1:
  #      ● Crops in loaded chunks will grow
  # Mode 2:
  #      ● Online players' crops will grow
  # Mode 3:
  #      ● Recommended Mode 1 + Mode 2
  # Mode 4:
  #      ● Please disable season in this mode!
  #      ● All the crops will grow
  #      ● If season not disabled, your server would be lagging when there's a lot of data
  #      ● Crop data would be removed as soon as they are ripe when season disabled, so it would not cause lag!
  grow-mode: 3
  # The time to start growing(ticks)
  # 1000ticks is 7am in game. (0-23999)
  # Sprinklers will work after all crops finish growing
  grow-time:
    - 1000
  # Time in random a single crop need to grow（seconds）
  # This prevents a large amount of crops grow at the same time
  # Large amount of block replacement would cause lag.
  time-to-grow: 60
  # Similar to "time-to-grow", this prevent all sprinklers work at the same time
  time-to-work: 30
  # Async Time Check (requires restart)
  # Crops might not grow when using async.
  # It is not really necessary to be Async
  async-time-check: false
  # Worlds where crops would grow
  whitelist-worlds:
    - world
  # Should all the worlds' crops grow?
  # This is useful for per player per world server.
  # In this mode, whitelist world can only have one for time & season judgment.
  all-world-grow: false
  # How does gigantic work?
  # In stardrew valley, crops will still absorb water every day after it is ripe to be gigantic
  # But you can give it only one chance to be gigantic(This is also good for performance)
  gigantic-only-one-try: false


  quality:
    # If disabled, you need to configurate the loots in ItemsAdder config
    enable: true
    # Default ratio
    default-ratio: 17/2/1



  # Water Amount to refill when using water bucket
  sprinkler-refill: 2
  # Water Amount to refill with a single click to water block
  water-can-refill: 1
  # Can watering-can add water to sprinklers?
  water-can-add-water-to-sprinkler: true
  # Should particles be displayed when using watering can?
  water-particles: true


  # Should the pot be dry even there's no crop on it
  # This would cost addition performance
  pot-dry-always-dry: false


  # Will bone meal accelerate the growth of crop
  bone-meal:
    enable: true
    chance: 0.5
    success-particle: VILLAGER_HAPPY



  # Should we limit the max amount of crops and sprinkler in one chunk
  # Recommended to enable because ItemsAdder might throw StackOverFlow
  # when there are too many custom blocks in one chunk
  limit:
    enable: true
    crop: 64
    sprinkler: 8



  # can player harvest crops with right click?
  # if set "false" crops can't be harvested repeatedly
  right-click-harvest: true
  # If "right-click-harvest" is true
  # Should player must harvest with empty hands?
  harvest-with-empty-hand: true
  # Should player be prevented from planting if wrong season
  prevent-plant-if-wrong-season: true
  # Should player be notified of the wrong season?
  should-notify-if-wrong-season: true