name: DraimFarming
version: '${version}'
main: net.draimcido.draimfarming.Main
api-version: 1.19
authors: [ DraimGooSe ]
description: Уникальная система фермерства для проекта DraimCiDo
website: https://dev.draimcido.net
depend:
  - ItemsAdder
  - ProtocolLib
softdepend:
  - PlaceholderAPI
  - Kingdoms
  - WorldGuard
  - Towny
  - Lands
  - GriefPrevention
  - mcMMO
  - AureliumSkills
  - MMOCore
  - EcoSkills
  - RealisticSeasons

commands:
  draimfarming:
    usage: /draimfarming <args>
    permission: draimfarming.admin
    aliases:
      - df
